# Bloco obrigatório para o Nginx gerir conexões (vazio = assume definições padrão)
events {}

# Bloco principal para configuração de tráfego HTTP
http {

    # Define o destino "product_service" apontando para o container interno na porta 8081
    upstream product_service {
        server product-service:8081;
    }

    # Define o destino "order_service" apontando para o container interno na porta 8082
    upstream order_service {
        server order-service:8082;
    }

    # Define o servidor público (o "porteiro" da aplicação)
    server {

	# O Nginx fica à escuta na porta 80 (HTTP padrão)
        listen 80;

	# Regra 1: Se o caminho do URL começar por "/products"
        location /products {

            # Encaminha o pedido para o cluster "product_service" definido no topo
            proxy_pass http://product_service;

            # Repassa o cabeçalho "Host" original do cliente
            proxy_set_header Host $host;

            # Repassa o IP real do cliente (senão o Spring Boot acharia que o IP era o do Nginx)
            proxy_set_header X-Real-IP $remote_addr;
        }

	# Regra 2: Se o caminho do URL começar por "/orders"
        location /orders {

            # Encaminha o pedido para o cluster "order_service" definido no topo
            proxy_pass http://order_service;

            # Mantém os cabeçalhos originais
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
