server.port=${SERVER_PORT:4000}
server.forward-headers-strategy=framework

spring.application.name=graphql-gateway

spring.graphql.graphiql.enabled=${GRAPHIQL_ENABLED:true}
spring.graphql.graphiql.path=/graphiql

app.services.users-url=${USERS_SERVICE_URL:http://localhost:3001}
app.services.orders-url=${ORDERS_SERVICE_URL:http://localhost:3002}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true