server.port=8080
spring.application.name=orders-api

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/${POSTGRES_DB:orders_db}
spring.datasource.username=${POSTGRES_USER:orders_user}
spring.datasource.password=${POSTGRES_PASSWORD:orders_password}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

spring.flyway.enabled=true

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_USER:app_user}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:app_password}
spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.publisher-returns=true

management.endpoints.web.exposure.include=health,info

app.outbox.batch-size=25
app.outbox.publish-delay-ms=2000
app.outbox.confirm-timeout-ms=5000