server.port=8081
spring.application.name=notifications-worker

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/${POSTGRES_DB:orders_db}
spring.datasource.username=${POSTGRES_USER:orders_user}
spring.datasource.password=${POSTGRES_PASSWORD:orders_password}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=false

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_USER:app_user}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:app_password}
spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.publisher-returns=true

spring.rabbitmq.listener.simple.acknowledge-mode=manual
spring.rabbitmq.listener.simple.prefetch=10
spring.rabbitmq.listener.simple.default-requeue-rejected=false

management.endpoints.web.exposure.include=health,info

app.worker.max-retries=${MAX_RETRIES:3}
